In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [54]:
((np.ones(20) * 2) ** np.arange(1, 21)) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [55]:
np.sum(((0.1 * np.ones(6)) ** (3 * np.arange(0, 6))) * ((0.2 * np.ones(6)) ** (4 * np.arange(0, 6))))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [ ]:
m = np.zeros((8,8), dtype=int)
m[1::2,::2] = 1
m[::2,1::2] = 1

print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [ ]:
m = np.random.random((5, 2))

p = np.zeros(m.shape)
p[:, 0] = np.sqrt(x[:, 0] + x[:, 1])
p[:, 1] = np.arctan(x[:, 1] / x[:, 0])

print(m, '\n', p)

[[0.91619854 0.1151249 ]
 [0.31163584 0.9740823 ]
 [0.02066908 0.50998329]
 [0.59425504 0.06896826]
 [0.61981516 0.22503172]]
[[0.56140465 1.56193125]
 [0.63543084 0.13475047]
 [1.16497155 0.50486757]
 [0.89830672 1.38872495]
 [0.9499161  1.30338926]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [16]:
m = np.random.random((10, 10))
p = m.argmax()

print(m, '\n', (p // 10, p % 10))

[[0.7775826  0.2330489  0.04541669 0.55527463 0.17398951 0.76935747
  0.29482099 0.49416208 0.66125873 0.37460602]
 [0.45323348 0.34478011 0.3558714  0.70981277 0.93421334 0.88428947
  0.3876758  0.84033389 0.18132901 0.45829294]
 [0.57157409 0.83444761 0.01518624 0.4457736  0.67275126 0.46045263
  0.26253535 0.51170008 0.31563454 0.46537032]
 [0.35683191 0.53948951 0.45878619 0.93685648 0.68565743 0.06575731
  0.29022145 0.93074838 0.42999499 0.11799977]
 [0.52294034 0.98388976 0.10482873 0.25348395 0.81508034 0.38259327
  0.91856417 0.13540563 0.21566722 0.30314754]
 [0.62111354 0.88215416 0.47190403 0.20935028 0.55797716 0.38742946
  0.7978446  0.64641425 0.49726613 0.65168696]
 [0.81174083 0.71850941 0.92727796 0.59492904 0.0356062  0.41361611
  0.42105631 0.1343611  0.76813856 0.42602206]
 [0.96290177 0.24356258 0.99406018 0.21745542 0.04964249 0.97747564
  0.38161216 0.35809828 0.26421697 0.46472215]
 [0.56770369 0.6807132  0.64817448 0.39499695 0.36107736 0.95014493
  0.77525963

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [17]:
m = np.random.random((10,2))
p = np.random.random((1, 2))

print(m, '\n', p)
print(m[sp.spatial.distance.cdist(m,p).argmin() % 10,:])

[[0.94105589 0.31633917]
 [0.98363922 0.1809853 ]
 [0.63730994 0.24855139]
 [0.19479072 0.05028591]
 [0.89156034 0.65267847]
 [0.93394179 0.14105326]
 [0.05324501 0.94048566]
 [0.07823549 0.66906101]
 [0.45665942 0.01324086]
 [0.35679124 0.56037821]] 
 [[0.47970028 0.15684846]]
[0.45665942 0.01324086]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [ ]:
m = np.linspace(-3, 3, 10)
 
p1 = x[x < 0] ** 2 + 2 * x[x < 0] + 6
p2 = x[(x >= 0) & (x <= 2)] + 6
p3 = x[x >= 2] ** 2 + 4 * x[x >= 2] - 4

print(m)
print(np.concatenate((p1,p2,p3), axis=0))

[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]
[ 9.          7.8365651   6.87257618  6.10803324  5.54293629  5.17728532
  5.01108033  5.04432133  5.27700831  5.70914127  6.15789474  6.47368421
  6.78947368  7.10526316  7.42105263  7.73684211  8.42382271 11.08310249
 13.94182825 17.        ]
[ 9.          7.8365651   6.87257618  6.10803324  5.54293629  5.17728532
  5.01108033  5.04432133  5.27700831  5.70914127  6.15789474  6.47368421
  6.78947368  7.10526316  7.42105263  7.73684211  8.42382271 11.08310249
 13.94182825 17.        ]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [14]:
X = np.random.random((3,3))
Y = X - X.mean(axis=1, keepdims=True)

print(X, '\n', Y)

[[0.44441224 0.8131891  0.8301317 ]
 [0.20617632 0.06986318 0.9711423 ]
 [0.74868045 0.04663287 0.11997363]] 
 [[-0.25149877  0.11727808  0.13422069]
 [-0.20955094 -0.34586409  0.55541503]
 [ 0.4435848  -0.25846278 -0.18512202]]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [15]:
X = np.random.normal(loc=0, scale=1.0, size=1000)

print(np.mean(X), np.var(X))

0.018721970490420667 0.9754768891297744


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [53]:
m = np.indices([5, 5])[1]
p = np.arange(0, 5) * (-1)

rows, column_indices = np.ogrid[:m.shape[0], :m.shape[1]]
p[p < 0] += m.shape[1]
column_indices = column_indices - p[:, np.newaxis]

print(m[rows, column_indices])

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [51]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[2, 0, 1, 0, 3]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [52]:
def opt_sample(x, c):
    assert len(x) > 0
    indexes = np.arange(0, len(x))
    prob = x / np.sum(x)
    return np.random.choice(indexes, size=c, p=prob)

            
opt_sample([50, 3, 1, 7, 20], 5) 

array([3, 0, 4, 0, 4])